name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: eifinger/setup-rye@v2
        with:
          enable-cache: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: rye sync

  lint:
    runs-on: ubuntu-latest
    needs: [deps]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: eifinger/setup-rye@v2
        with:
          enable-cache: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint code
        run: rye check
      - name: Check formatting
        run: rye format --check

  types:
    runs-on: ubuntu-latest
    needs: [deps]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: eifinger/setup-rye@v2
        with:
          enable-cache: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: rye sync
      - name: Check types
        run: ./.venv/bin/mypy .

  test:
    runs-on: ubuntu-latest
    needs: [deps]
    permissions:
      issues: write
      pull-requests: write
    strategy:
      matrix:
        python-version:
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: eifinger/setup-rye@v2
        with:
          enable-cache: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: rye sync
      - name: Run pytest
        run: |
          ./.venv/bin/pytest --junitxml=pytest.xml --cov=rugged --cov-report=xml:coverage.xml tests/ | tee pytest-coverage.txt
      - name: Comment PR
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./coverage.xml
          junitxml-path: ./pytest.xml


